# Generated by Django 2.2.27 on 2022-02-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='institute',
            new_name='institution',
        ),
    ]
